SHARED: &shared
  DEBUG: False
  NOT_FOUND_TITLE_DEFAULT: 'Página não encontrada'
  BATTLE_STATUS_TITLE_DEFAULT: 'Status da Batalha #{}'


DEVELOPMENT: &development
  <<: *shared
  DEBUG: True
  REDIS_URL: 'redis://localhost:6379/0'

TESTING:
  <<: *shared
  REDIS_URL: 'redis://morty'
